--- # multi tasks
- hosts: dev
  user: tata
  become: yes
  connection: ssh
  gather_facts: yes


  tasks:
   - name: install apache
     action: yum pkg=httpd state=present


   - name: start apache
     action: service name=httpd state=started    

   - name: copy index
     action: copy src=index.html dest=/var/www/html    
