--- #loops
- hosts: dev
  user: tata
  become: yes




  tasks:
    - name: create users
      user: name="{{item}}" state=present
      loop:
        - "viki"
        - "vitthal"
        - "shubham"  
