--- # 2 targets
- hosts: dev[0]
  user: tata
  become: yes
  connection: ssh
  gather_facts: yes


  tasks:
    - name: remove tree
      action: yum pkg=tree state=absent



- hosts: qa[0] 
  user: tata
  become: yes
  connection: ssh
  gather_facts: yes


  tasks: 
    - name: remove tree
      action: yum pkg=tree state=absent


    - name: install git
      action: yum pkg=git  state=present



