--- # variable def

- hosts: qa
  user: tata
  become: yes
  connection: ssh
  gather_facts: yes


  vars: 
    pkgname: httpd
    index_path: /var/www/html



  tasks:
    - name: install apache
      action: yum pkg="{{pkgname}}" state=present
    - name: start apache
      action: service name="{{pkgname}}" state=started
    - name: copy index
      action: copy src=index.html dest="{{index_path}}" 


- hosts: dev
  user: tata
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    pkg: tree

  tasks: 
   - name: install tree
     action: yum pkg="{{pkg}}" state=present    
